In [1]:
#Q.1- Write a Python Program to Add Two Matrices?

#Solution- 

import numpy as np

mydata = np.arange(0,20)
mat1 = np.reshape(mydata, (5,4))
mat2 = np.reshape(mydata, (5,4), 'f')

print("First matrix is \n",mat1)
print("Second matrix is \n",mat2)
print("Sum of the matrices are - \n",np.add(mat1,mat2))

First matrix is 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Second matrix is 
 [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
Sum of the matrices are - 
 [[ 0  6 12 18]
 [ 5 11 17 23]
 [10 16 22 28]
 [15 21 27 33]
 [20 26 32 38]]


In [2]:
#Q.2- Write a Python Program to Multiply Two Matrices?

#Solution- 

import numpy as np

mydata = np.arange(0,20)
mat1 = np.reshape(mydata, (5,4))
mat2 = np.reshape(mydata, (5,4), 'f')

print("First matrix is \n",mat1)
print("Second matrix is \n",mat2)
print("Multiplication of two matrices are - \n",np.multiply(mat1,mat2))

First matrix is 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Second matrix is 
 [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
Multiplication of two matrices are - 
 [[  0   5  20  45]
 [  4  30  66 112]
 [ 16  63 120 187]
 [ 36 104 182 270]
 [ 64 153 252 361]]


In [3]:
#Q.3- Write a Python Program to Transpose a Matrix?

#Solution- 

import numpy as np

mydata = np.arange(0,20)
mat1 = np.reshape(mydata, (5,4))
print("The matrix before transpose is \n",mat1)
print("The matrix after transpose is \n",mat1.transpose())

The matrix before transpose is 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
The matrix after transpose is 
 [[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [8]:
#Q.4- Write a Python Program to Sort Words in Alphabetic Order?

#Solution- 

def split_and_sort(a):
    to_lower = a.lower()
    split = to_lower.split()
    words_list = []
    for word in split:
        words_list.append(word)
    words_list.sort()
    return(words_list)
    
User_input = "Hello This is Harit prem Rajput"
print ("The string is:- ",User_input)
print("The string after sort is ",split_and_sort(User_input))

The string is:-  Hello This is Harit prem Rajput
The string after sort is  ['harit', 'hello', 'is', 'prem', 'rajput', 'this']


In [10]:
#Q.5- Write a Python Program to Remove Punctuation From a String?

#Solution- 

import string

User_input = "Hello! This is Harit."
print ("The string is:- ",User_input)
print("The string after removing punctuation is:- ",User_input.translate(User_input.maketrans(' ', ' ',string.punctuation)))

The string is:-  Hello! This is Harit.
The string after removing punctuation is:-  Hello This is Harit
